---
name: CI

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v.*
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests on macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - run: make test -C "$GITHUB_WORKSPACE"

  tests on linux:
    runs-on: ubuntu-latest
    steps:
      - run: make dockertest -C "$GITHUB_WORKSPACE"

  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/syntax-check@v1

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fish-actions/install-fish@v1
      - uses: fish-actions/format-check@v1

  mega-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oxsecurity/megalinter/flavors/documentation@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
